"""CLI entry point for Swagger Scanner."""

import os
import sys

import click

from .fetcher import fetch_openapi
from .md_generator import generate_index_markdown, generate_per_tag_markdown
from .parser import parse_endpoints, parse_schemas
from .ts_generator import generate_per_tag_typescript


@click.command()
@click.argument("url")
@click.option(
    "-o",
    "--output",
    default="./docs",
    help="Output directory path (default: ./docs)",
)
@click.option(
    "--types-output",
    default=None,
    help=(
        "Optional directory for generated TypeScript type modules. "
        "When omitted, only Markdown files are generated."
    ),
)
@click.option(
    "--types-filename-style",
    type=click.Choice(["tag", "singular"]),
    default="tag",
    show_default=True,
    help="Filename style for generated TypeScript modules.",
)
@click.option(
    "--types-any",
    type=click.Choice(["any", "unknown"]),
    default="unknown",
    show_default=True,
    help="Fallback TypeScript type for unknown OpenAPI schemas in generated modules.",
)
@click.option(
    "--types-data-only",
    is_flag=True,
    help="Generate only API data/domain types, omitting response wrappers and API metadata/error schemas.",
)
def main(
    url: str,
    output: str,
    types_output: str | None,
    types_filename_style: str,
    types_any: str,
    types_data_only: bool,
) -> None:
    """Scan OpenAPI v3 JSON and generate Markdown documentation.

    URL is the endpoint to fetch OpenAPI JSON from (e.g., http://localhost:8000/openapi.json)

    Output will be a directory with one file per tag, plus an index.md file.
    """
    click.echo(f"Fetching OpenAPI spec from {url}...")

    try:
        openapi = fetch_openapi(url)
    except Exception as e:
        click.echo(f"Error fetching OpenAPI spec: {e}", err=True)
        sys.exit(1)

    info = openapi.get("info", {})
    title = info.get("title", "Unknown API")
    version = info.get("version", "unknown")
    click.echo(f"Parsing: {title} (v{version})")

    endpoints, inline_schemas = parse_endpoints(openapi)
    click.echo(f"Found {len(endpoints)} endpoints")

    schemas = parse_schemas(openapi)
    click.echo(f"Found {len(schemas)} schemas")

    # Merge inline schemas with component schemas
    all_schemas = {**schemas, **inline_schemas}
    if inline_schemas:
        click.echo(f"Found {len(inline_schemas)} inline schemas")

    os.makedirs(output, exist_ok=True)

    tag_files = generate_per_tag_markdown(openapi, endpoints, all_schemas)
    for filename, content in tag_files.items():
        filepath = os.path.join(output, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        click.echo(f"  Created: {filepath}")

    index_content = generate_index_markdown(openapi, endpoints)
    index_path = os.path.join(output, "index.md")
    with open(index_path, "w", encoding="utf-8") as f:
        f.write(index_content)
    click.echo(f"  Created: {index_path}")

    type_file_count = 0
    if types_output:
        os.makedirs(types_output, exist_ok=True)
        header = "/* Auto-generated by swagger-scanner. Do not edit manually. */"
        type_files = generate_per_tag_typescript(
            endpoints,
            all_schemas,
            export=True,
            any_type=types_any,
            filename_style=types_filename_style,
            header=header,
            data_only=types_data_only,
        )
        for filename, content in type_files.items():
            filepath = os.path.join(types_output, filename)
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(content)
            click.echo(f"  Created: {filepath}")
        type_file_count = len(type_files)

    click.echo(f"\nDocumentation written to {output}/ ({len(tag_files) + 1} files)")
    if types_output:
        click.echo(f"TypeScript types written to {types_output}/ ({type_file_count} files)")


if __name__ == "__main__":
    main()
